[package]
name = "vr-threading"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vr-logger = { path = "../vr-logger" }
crossbeam = { version = "0.8.4", default-features = false, features = ["std"] }
