[package]
name = "vr-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vr-logger= { path = "../vr-logger" }
vr-threading = { path = "../vr-threading" }
